apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-26T14:01:59Z"
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: default
  resourceVersion: "12440"
  uid: 6c28a7c5-461a-4674-a0f0-2da2278864d0
spec:
  clusterIP: 10.101.179.208
  clusterIPs:
  - 10.101.179.208
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 99
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
